export { ReactComponent as FoodCoverIcon } from "assets/icons/food-cover.svg";
export { ReactComponent as InvoiceIcon } from "assets/icons/invoice.svg";
export { ReactComponent as LogoIcon } from "assets/icons/logo.svg";
export { ReactComponent as BellIcon } from "assets/icons/bell.svg";
export { ReactComponent as CrownIcon } from "assets/icons/crown.svg";
export { ReactComponent as CakeIcon } from "assets/icons/cake.svg";
export { ReactComponent as DollarIcon } from "assets/icons/dollar.svg";
export { ReactComponent as TargetIcon } from "assets/icons/target.svg";
export { ReactComponent as SpeedometerIcon } from "assets/icons/speedometer.svg";
